#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
# Source0 file verified with key 0x30A59377A7763BE6 (slouken@libsdl.org)
#
Name     : compat-SDL2-soname1
Version  : 2.0.5
Release  : 11
URL      : https://www.libsdl.org/release/SDL2-2.0.5.tar.gz
Source0  : https://www.libsdl.org/release/SDL2-2.0.5.tar.gz
Source99 : https://www.libsdl.org/release/SDL2-2.0.5.tar.gz.sig
Summary  : Simple DirectMedia Layer
Group    : Development/Tools
License  : CPL-1.0 Zlib
Requires: compat-SDL2-soname1-bin = %{version}-%{release}
Requires: compat-SDL2-soname1-lib = %{version}-%{release}
Requires: compat-SDL2-soname1-license = %{version}-%{release}
BuildRequires : buildreq-cmake
BuildRequires : gcc-dev32
BuildRequires : gcc-libgcc32
BuildRequires : gcc-libstdc++32
BuildRequires : glibc-dev32
BuildRequires : glibc-libc32
BuildRequires : libXxf86vm-dev
BuildRequires : libXxf86vm-dev32
BuildRequires : pkgconfig(32alsa)
BuildRequires : pkgconfig(32dbus-1)
BuildRequires : pkgconfig(32egl)
BuildRequires : pkgconfig(32gl)
BuildRequires : pkgconfig(32libpulse-simple)
BuildRequires : pkgconfig(32libusb-1.0)
BuildRequires : pkgconfig(32wayland-client)
BuildRequires : pkgconfig(32wayland-cursor)
BuildRequires : pkgconfig(32wayland-egl)
BuildRequires : pkgconfig(32wayland-scanner)
BuildRequires : pkgconfig(32x11)
BuildRequires : pkgconfig(32xcursor)
BuildRequires : pkgconfig(32xext)
BuildRequires : pkgconfig(32xi)
BuildRequires : pkgconfig(32xinerama)
BuildRequires : pkgconfig(32xkbcommon)
BuildRequires : pkgconfig(32xrandr)
BuildRequires : pkgconfig(alsa)
BuildRequires : pkgconfig(dbus-1)
BuildRequires : pkgconfig(egl)
BuildRequires : pkgconfig(gl)
BuildRequires : pkgconfig(libpulse-simple)
BuildRequires : pkgconfig(libusb-1.0)
BuildRequires : pkgconfig(wayland-client)
BuildRequires : pkgconfig(wayland-cursor)
BuildRequires : pkgconfig(wayland-egl)
BuildRequires : pkgconfig(wayland-scanner)
BuildRequires : pkgconfig(x11)
BuildRequires : pkgconfig(xcursor)
BuildRequires : pkgconfig(xext)
BuildRequires : pkgconfig(xi)
BuildRequires : pkgconfig(xinerama)
BuildRequires : pkgconfig(xkbcommon)
BuildRequires : pkgconfig(xrandr)
Patch1: CVE-2019-7635.patch

%description
This is the Simple DirectMedia Layer, a generic API that provides low
level access to audio, keyboard, mouse, and display framebuffer across
multiple platforms.

%package bin
Summary: bin components for the compat-SDL2-soname1 package.
Group: Binaries
Requires: compat-SDL2-soname1-license = %{version}-%{release}

%description bin
bin components for the compat-SDL2-soname1 package.


%package dev
Summary: dev components for the compat-SDL2-soname1 package.
Group: Development
Requires: compat-SDL2-soname1-lib = %{version}-%{release}
Requires: compat-SDL2-soname1-bin = %{version}-%{release}
Provides: compat-SDL2-soname1-devel = %{version}-%{release}
Requires: compat-SDL2-soname1 = %{version}-%{release}

%description dev
dev components for the compat-SDL2-soname1 package.


%package dev32
Summary: dev32 components for the compat-SDL2-soname1 package.
Group: Default
Requires: compat-SDL2-soname1-lib32 = %{version}-%{release}
Requires: compat-SDL2-soname1-bin = %{version}-%{release}
Requires: compat-SDL2-soname1-dev = %{version}-%{release}

%description dev32
dev32 components for the compat-SDL2-soname1 package.


%package lib
Summary: lib components for the compat-SDL2-soname1 package.
Group: Libraries
Requires: compat-SDL2-soname1-license = %{version}-%{release}

%description lib
lib components for the compat-SDL2-soname1 package.


%package lib32
Summary: lib32 components for the compat-SDL2-soname1 package.
Group: Default
Requires: compat-SDL2-soname1-license = %{version}-%{release}

%description lib32
lib32 components for the compat-SDL2-soname1 package.


%package license
Summary: license components for the compat-SDL2-soname1 package.
Group: Default

%description license
license components for the compat-SDL2-soname1 package.


%prep
%setup -q -n SDL2-2.0.5
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1560290989
mkdir -p clr-build
pushd clr-build
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
%cmake .. -DVIDEO_WAYLAND=off -DWAYLAND_SHARED=off
make  %{?_smp_mflags} VERBOSE=1
popd
mkdir -p clr-build32
pushd clr-build32
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
export FCFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
export FFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=4 -fstack-protector-strong -mzero-caller-saved-regs=used "
export PKG_CONFIG_PATH="/usr/lib32/pkgconfig"
export ASFLAGS="${ASFLAGS}${ASFLAGS:+ }--32"
export CFLAGS="${CFLAGS}${CFLAGS:+ }-m32"
export CXXFLAGS="${CXXFLAGS}${CXXFLAGS:+ }-m32"
export LDFLAGS="${LDFLAGS}${LDFLAGS:+ }-m32"
%cmake -DLIB_INSTALL_DIR:PATH=/usr/lib32 -DCMAKE_INSTALL_LIBDIR=/usr/lib32 -DLIB_SUFFIX=32 .. -DVIDEO_WAYLAND=off -DWAYLAND_SHARED=off
make  %{?_smp_mflags} VERBOSE=1
unset PKG_CONFIG_PATH
popd

%install
export SOURCE_DATE_EPOCH=1560290989
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/compat-SDL2-soname1
cp COPYING.txt %{buildroot}/usr/share/package-licenses/compat-SDL2-soname1/COPYING.txt
cp Xcode-iOS/Demos/data/bitmapfont/license.txt %{buildroot}/usr/share/package-licenses/compat-SDL2-soname1/Xcode-iOS_Demos_data_bitmapfont_license.txt
cp Xcode/SDL/pkg-support/resources/License.txt %{buildroot}/usr/share/package-licenses/compat-SDL2-soname1/Xcode_SDL_pkg-support_resources_License.txt
pushd clr-build32
%make_install32
if [ -d  %{buildroot}/usr/lib32/pkgconfig ]
then
pushd %{buildroot}/usr/lib32/pkgconfig
for i in *.pc ; do ln -s $i 32$i ; done
popd
fi
popd
pushd clr-build
%make_install
popd

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
%exclude /usr/bin/sdl2-config

%files dev
%defattr(-,root,root,-)
%exclude /usr/include/SDL2/SDL.h
%exclude /usr/include/SDL2/SDL_assert.h
%exclude /usr/include/SDL2/SDL_atomic.h
%exclude /usr/include/SDL2/SDL_audio.h
%exclude /usr/include/SDL2/SDL_bits.h
%exclude /usr/include/SDL2/SDL_blendmode.h
%exclude /usr/include/SDL2/SDL_clipboard.h
%exclude /usr/include/SDL2/SDL_config.h
%exclude /usr/include/SDL2/SDL_config_android.h
%exclude /usr/include/SDL2/SDL_config_iphoneos.h
%exclude /usr/include/SDL2/SDL_config_macosx.h
%exclude /usr/include/SDL2/SDL_config_minimal.h
%exclude /usr/include/SDL2/SDL_config_pandora.h
%exclude /usr/include/SDL2/SDL_config_psp.h
%exclude /usr/include/SDL2/SDL_config_windows.h
%exclude /usr/include/SDL2/SDL_config_winrt.h
%exclude /usr/include/SDL2/SDL_config_wiz.h
%exclude /usr/include/SDL2/SDL_copying.h
%exclude /usr/include/SDL2/SDL_cpuinfo.h
%exclude /usr/include/SDL2/SDL_egl.h
%exclude /usr/include/SDL2/SDL_endian.h
%exclude /usr/include/SDL2/SDL_error.h
%exclude /usr/include/SDL2/SDL_events.h
%exclude /usr/include/SDL2/SDL_filesystem.h
%exclude /usr/include/SDL2/SDL_gamecontroller.h
%exclude /usr/include/SDL2/SDL_gesture.h
%exclude /usr/include/SDL2/SDL_haptic.h
%exclude /usr/include/SDL2/SDL_hints.h
%exclude /usr/include/SDL2/SDL_joystick.h
%exclude /usr/include/SDL2/SDL_keyboard.h
%exclude /usr/include/SDL2/SDL_keycode.h
%exclude /usr/include/SDL2/SDL_loadso.h
%exclude /usr/include/SDL2/SDL_log.h
%exclude /usr/include/SDL2/SDL_main.h
%exclude /usr/include/SDL2/SDL_messagebox.h
%exclude /usr/include/SDL2/SDL_mouse.h
%exclude /usr/include/SDL2/SDL_mutex.h
%exclude /usr/include/SDL2/SDL_name.h
%exclude /usr/include/SDL2/SDL_opengl.h
%exclude /usr/include/SDL2/SDL_opengl_glext.h
%exclude /usr/include/SDL2/SDL_opengles.h
%exclude /usr/include/SDL2/SDL_opengles2.h
%exclude /usr/include/SDL2/SDL_opengles2_gl2.h
%exclude /usr/include/SDL2/SDL_opengles2_gl2ext.h
%exclude /usr/include/SDL2/SDL_opengles2_gl2platform.h
%exclude /usr/include/SDL2/SDL_opengles2_khrplatform.h
%exclude /usr/include/SDL2/SDL_pixels.h
%exclude /usr/include/SDL2/SDL_platform.h
%exclude /usr/include/SDL2/SDL_power.h
%exclude /usr/include/SDL2/SDL_quit.h
%exclude /usr/include/SDL2/SDL_rect.h
%exclude /usr/include/SDL2/SDL_render.h
%exclude /usr/include/SDL2/SDL_revision.h
%exclude /usr/include/SDL2/SDL_rwops.h
%exclude /usr/include/SDL2/SDL_scancode.h
%exclude /usr/include/SDL2/SDL_shape.h
%exclude /usr/include/SDL2/SDL_stdinc.h
%exclude /usr/include/SDL2/SDL_surface.h
%exclude /usr/include/SDL2/SDL_system.h
%exclude /usr/include/SDL2/SDL_syswm.h
%exclude /usr/include/SDL2/SDL_test.h
%exclude /usr/include/SDL2/SDL_test_assert.h
%exclude /usr/include/SDL2/SDL_test_common.h
%exclude /usr/include/SDL2/SDL_test_compare.h
%exclude /usr/include/SDL2/SDL_test_crc32.h
%exclude /usr/include/SDL2/SDL_test_font.h
%exclude /usr/include/SDL2/SDL_test_fuzzer.h
%exclude /usr/include/SDL2/SDL_test_harness.h
%exclude /usr/include/SDL2/SDL_test_images.h
%exclude /usr/include/SDL2/SDL_test_log.h
%exclude /usr/include/SDL2/SDL_test_md5.h
%exclude /usr/include/SDL2/SDL_test_random.h
%exclude /usr/include/SDL2/SDL_thread.h
%exclude /usr/include/SDL2/SDL_timer.h
%exclude /usr/include/SDL2/SDL_touch.h
%exclude /usr/include/SDL2/SDL_types.h
%exclude /usr/include/SDL2/SDL_version.h
%exclude /usr/include/SDL2/SDL_video.h
%exclude /usr/include/SDL2/begin_code.h
%exclude /usr/include/SDL2/close_code.h
%exclude /usr/lib64/libSDL2-2.0.so
%exclude /usr/lib64/libSDL2.so
%exclude /usr/lib64/pkgconfig/sdl2.pc
%exclude /usr/share/aclocal/sdl2.m4

%files dev32
%defattr(-,root,root,-)
%exclude /usr/lib32/libSDL2-2.0.so
%exclude /usr/lib32/libSDL2.so
%exclude /usr/lib32/pkgconfig/32sdl2.pc
%exclude /usr/lib32/pkgconfig/sdl2.pc

%files lib
%defattr(-,root,root,-)
/usr/lib64/libSDL2-2.0.so.0.4.1
/usr/lib64/libSDL2-2.0.so.1

%files lib32
%defattr(-,root,root,-)
/usr/lib32/libSDL2-2.0.so.0.4.1
/usr/lib32/libSDL2-2.0.so.1

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/compat-SDL2-soname1/COPYING.txt
/usr/share/package-licenses/compat-SDL2-soname1/Xcode-iOS_Demos_data_bitmapfont_license.txt
/usr/share/package-licenses/compat-SDL2-soname1/Xcode_SDL_pkg-support_resources_License.txt
